version: "3.9"

services:
    api_server:
      image: api_server
      container_name: api_server
      ports:
        - "80:8001"
      volumes:
        - /home/a10955psys/werewolf_kill_server/logs:/usr/src/app/game_logs
      build:
        context: ./werewolf_kill_server
        dockerfile: dockerfile
    grpc_server:
      image: grpc_server
        container_name: grpc_server
        build:
          context: ./werewolf_kill
          dockerfile: Dockerfile