version: "3.9"

services:
    api_server:
      image: api_server
      container_name: api_server
      # ports:
      #   - "80:8001"
      volumes:
        - /home/a10955psys/werewolf_kill_server/logs:/usr/src/app/game_logs
      build:
        context: ./werewolf_kill_server
        dockerfile: dockerfile
      environment:
        werewolf_server_ip : "werewolf_server:50051"
        agent_server_ip : "agent_server:50052"
        jwt_open : 1
        TZ : Asia/Taipei
    werewolf_server:
      image: werewolf_server
      container_name: werewolf_server
      build:
        context: ./werewolf_kill
        dockerfile: Dockerfile
    agent_server:
      image: agent_server
      container_name: agent_server
      build:
        context: ./generative_agent_with_werewolf_kill
        dockerfile: dockerfile
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    front:
      image: nginx
      container_name: werewolf_kill
      volumes:
        - /home/a10955psys/werewolf_kill_server/wolf/nginx.conf:/etc/nginx/conf.d/default.conf
        - /home/a10955psys/werewolf_kill_server/wolf/:/usr/share/nginx/html
      ports:
        - "80:80"