version: "3.9"

services:
    api_server:
      image: api_server
      container_name: api_server
      # ports:
      #   - "80:8001"
      volumes:
        - ./logs/api_server_logs:/usr/src/app/game_logs
      build:
        context: ./werewolf_kill_server
        dockerfile: dockerfile
      environment:
        werewolf_server_ip : "werewolf_server:50051"
        agent_server_ip : "agent_server:50052"
        jwt_open : 1
        TZ : Asia/Taipei
      logging:
          options:
            max-size: 5m
    werewolf_server:
      image: werewolf_server
      container_name: werewolf_server
      build:
        context: ./werewolf_kill
        dockerfile: Dockerfile
    agent_server:
      image: agent_server
      container_name: agent_server
      build:
        context: ./generative_agent_with_werewolf_kill
        dockerfile: dockerfile
      environment:
        api_server_ip : "http://api_server:8001"
      volumes:
        - ./logs/agent_logs:/usr/src/app/agent/logs
        - ./logs/game_info:/usr/src/app/agent/doc/game_info
        - ./doc/secret/:/usr/src/app/agent/doc/secret
        - ./doc/summary/:/usr/src/app/agent/doc/summary
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
      logging:
        options:
          max-size: 5m
    front:
      image: nginx
      container_name: werewolf_kill
      volumes:
        - ./werewolf_kill_server/views/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./werewolf_kill_server/views/:/usr/share/nginx/html
        - ./logs/nginx_logs:/var/log/nginx/
      ports:
        - "80:80"
      logging:
        options:
          max-size: 50k